application: amberzju2014
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /cors
  static_dir: cors
- url: /img
  static_dir: img
- url: /(favicon\.ico|robots\.txt)
  static_files: static/\1
  upload: static/(.*)
- url: /api.*
  script: web_api.application
- url: /.*
  script: web_ui.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
